name: Actions Workflow

# on: [push, pull_request]
on:
  repository_dispatch:
    types: [build]

  # push: 
  pull_request: 
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
        # retriving payload values from Postman
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List files
        run: |
          pwd
          ls 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after Checkout
        run: |
          pwd
          ls -la 

      - name: Simple JS Action
        id: greet
        # github url at the end @master or @version or @commitNumber
        uses: actions/hello-world-javascript-action@v1
        # parameters
        with: 
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"


#  setup Postman:
#  Request: Post -> url: https://api.github.com/repos/shamal112mn/github-action-test/dispatches

#  authorization: generate token

#  Headers:
#  Accept: application/vnd.github.everest-preview+json
#  content-Type: application/json

#   Body:
#   {
#     "event_type": "build",
#     "client_payload": {
#       "env": "production"
#       }
#   }

