name: Python Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print a string
        run: print ("Hello from Python!")
        shell: python
       